CREATE TABLE  TBPRODUCTOS
(
  ID             VARCHAR 15  PK
  NOMBREPRODUCTO         VARCHAR 50 
) ;

php artisan make:model TBPRODUCTOS -m
php artisan make:model TBBANCOS -m
php artisan make:model TBLINEAS -m
php artisan make:model TBTIPOTASAS -m
php artisan make:model TBEMPRESAS -m
php artisan make:model TBPLANPAGOS -m
php artisan make:model TBPRODUCTOS -m
php artisan make:model TBPRODUCTOS -m


 
CREATE TABLE  TBBANCOS
(
  ID              VARCHAR 15 PK
  NOMBREBANCO          VARCHAR 50,
) ;
 
 
CREATE TABLE  TBLINEAS
(
  ID             VARCHAR 15 PK
  NOMBRELINEA        VARCHAR 50
) ;

CREATE TABLE  TBTIPOTASAS
(
  ID             VARCHAR 15 PK
  NOMBRETIPOTASA        VARCHAR 50
  PORCENTAJE       NUMBER(8,2),
  
) ;


CREATE TABLE  TBEMPRESAS
(
  ID             VARCHAR 15 PK
  NOMBREEMPRESA        VARCHAR 50 
  
) ;



CREATE TABLE TBPRESTAMOS
( ID 
  EMPRESA_ID                VARCHAR2(50 BYTE),
  NUMERO_PRESTAMO           VARCHAR2(25 BYTE),  
  CODIGO_BANCO_ID              VARCHAR2(50 BYTE),
  NUMERO_LINEA_ID              VARCHAR2(50 BYTE),
  FORMAPAGO               VARCHAR2(1 BYTE) , // 'A'ADELANTADO / 'V' VENCIEMINTO
  MONEDA                  VARCHAR2(5 BYTE) , // 'USD', 'CRC' , 'EUR'  
  FECHA_FORMALIZACION        DATE, 
  FECHA_VENCIMIENTO          DATE,
  FECHA_PROXIMO_PAGO      DATE,
  MONTO_PRESTAMO             NUMBER(17,2),  
  SALDO_PRESTAMO             NUMBER(17,2),
  PLAZO_MESES               NUMBER(3),
  TIPO_TASA_ID                 VARCHAR2(15 BYTE),
  TASA_INTERES              NUMBER(17,4),  
  TASA_SPREDD               NUMBER(12,8),  
  CUENTA_DESEMBOLSO       VARCHAR2(100 BYTE),
  ESTADO       VARCHAR2(1 BYTE)   'A' ACTIVO 'E' ELABORACION, 'L' LIQUIDADO,  
  PERIODICIDA_DPAGO          NUMBER(15)    1= Anualmente, 2= Semestralmente, 3= Cuatrimestralmente, 4= Trimestralmente, 6= Bimestralmente, 12 = MENSUAL, 
  OBSERVACION                VARCHAR2(255 BYTE)
) ;


CREATE TABLE TBPLANPAGOS
( PRESTAMO_ID 
  NUMERO_CUOTA               NUMBER(15)       DEFAULT 0,
  FECHA_PAGO              DATE             DEFAULT SYSDATE,
  MONTO_PRINCIPAL           NUMBER(17,2)     DEFAULT 0.00,
  MONTON_INTERES             NUMBER(17,2)     DEFAULT 0.00,  
  MONTO_SEGURO            NUMBER(17,2)     DEFAULT 0.00,
  MONTO_OTROS             NUMBER(17,2)     DEFAULT 0.00,
  SALDO_PRESTAMO            NUMBER(17,2)     DEFAULT 0.00,
  TASA_INTERES            NUMBER(8,4)      DEFAULT 0,  
  SALDO_PRINCIPAL           NUMBER(17,2),
  SALDO_INTERES             NUMBER(17,2),
  SALDO_SEGURO              NUMBER(17,2),
  SALDO_OTROS          NUMBER(20,5),
  OBSERVACION             VARCHAR2(255 BYTE),
    
) ;



**CREATE TABLE TBTASASXPERIODOS
( EMPRESA         VARCHAR2(10 BYTE),
  NUM_PRESTAMO   NUMBER(30),
  NUM_LINEA   NUMBER(15),
  NUM_REGISTRO NUMBER(5),
  NUM_CUOTA_INICIO    NUMBER(15),
  NUM_CUOTA_FIN       NUMBER(15),
  TIPO_TASA           VARCHAR2(5 BYTE),
  TASA_SPREDD  NUMBER(12,8),
  TASA_PISO           NUMBER(12,8),
  TASA_TECHO          NUMBER(12,8),
  OBSERVACION         VARCHAR2(2000 BYTE),
  CREADO_POR          VARCHAR2(30 BYTE),
  FECHA_CREADO        DATE,
  MODIFICADO_POR      VARCHAR2(30 BYTE),
  FECHA_MODIFICADO    DATE,
  IND_GRACIA_PRINCIPAL    CHAR(1 BYTE),
  IND_GRACIA_INTERES      CHAR(1 BYTE)
  IND_GRACIA_SEGURO       CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
 
                         
         